package edu.nuaa.wwn.ad.dao;

import edu.nuaa.wwn.ad.entity.UserPO;
import org.apache.ibatis.annotations.Param;

public interface UserPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_t
     *
     * @mbg.generated Wed Sep 02 17:28:51 CST 2020
     */
    int deleteByPrimaryKey(Integer userId);

    UserPO selectByUserName(@Param("username") String username);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_t
     *
     * @mbg.generated Wed Sep 02 17:28:51 CST 2020
     */
    int insert(UserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_t
     *
     * @mbg.generated Wed Sep 02 17:28:51 CST 2020
     */
    int insertSelective(UserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_t
     *
     * @mbg.generated Wed Sep 02 17:28:51 CST 2020
     */
    UserPO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_t
     *
     * @mbg.generated Wed Sep 02 17:28:51 CST 2020
     */
    int updateByPrimaryKeySelective(UserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user_t
     *
     * @mbg.generated Wed Sep 02 17:28:51 CST 2020
     */
    int updateByPrimaryKey(UserPO record);
}