package edu.nuaa.wwn.ad.dao;

import edu.nuaa.wwn.ad.entity.CreativePO;

public interface CreativePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_creative
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_creative
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int insert(CreativePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_creative
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int insertSelective(CreativePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_creative
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    CreativePO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_creative
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int updateByPrimaryKeySelective(CreativePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_creative
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int updateByPrimaryKey(CreativePO record);
}