package edu.nuaa.wwn.ad.dao;

import edu.nuaa.wwn.ad.entity.UnitPO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UnitPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    UnitPO findByPlanIdAndUniName(@Param("planId") Long planId, @Param("unitName") String unitName);

    List<UnitPO> findAllByIds(@Param("ids") List<Long> ids);

    List<UnitPO> findAllByStatus(@Param("status") Integer status);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int insert(UnitPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int insertSelective(UnitPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    UnitPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int updateByPrimaryKeySelective(UnitPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int updateByPrimaryKey(UnitPO record);
}