package edu.nuaa.wwn.ad.dao;

import edu.nuaa.wwn.ad.entity.UnitDistrictPO;
import org.springframework.stereotype.Repository;

@Repository
public interface UnitDistrictPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit_district
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit_district
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    long insert(UnitDistrictPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit_district
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    long insertSelective(UnitDistrictPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit_district
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    UnitDistrictPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit_district
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int updateByPrimaryKeySelective(UnitDistrictPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit_district
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int updateByPrimaryKey(UnitDistrictPO record);
}