package edu.nuaa.wwn.ad.dao;

import edu.nuaa.wwn.ad.entity.UnitItPO;
import org.springframework.stereotype.Repository;

@Repository
public interface UnitItPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit_it
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit_it
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    long insert(UnitItPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit_it
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    long insertSelective(UnitItPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit_it
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    UnitItPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit_it
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int updateByPrimaryKeySelective(UnitItPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_unit_it
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int updateByPrimaryKey(UnitItPO record);
}