package edu.nuaa.wwn.ad.dao;

import edu.nuaa.wwn.ad.entity.UserPO;
import feign.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    UserPO findByUsername(@Param("username") String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int insert(UserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int insertSelective(UserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    UserPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int updateByPrimaryKeySelective(UserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_user
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    int updateByPrimaryKey(UserPO record);
}