package edu.nuaa.wwn.ad.entity;

public class CreativeUnitPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creative_unit.id
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creative_unit.creative_id
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private Long creativeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creative_unit.unit_id
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private Long unitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creative_unit.id
     *
     * @return the value of creative_unit.id
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creative_unit.id
     *
     * @param id the value for creative_unit.id
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creative_unit.creative_id
     *
     * @return the value of creative_unit.creative_id
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public Long getCreativeId() {
        return creativeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creative_unit.creative_id
     *
     * @param creativeId the value for creative_unit.creative_id
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setCreativeId(Long creativeId) {
        this.creativeId = creativeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creative_unit.unit_id
     *
     * @return the value of creative_unit.unit_id
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public Long getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creative_unit.unit_id
     *
     * @param unitId the value for creative_unit.unit_id
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setUnitId(Long unitId) {
        this.unitId = unitId;
    }
}