package edu.nuaa.wwn.ad.entity;

import java.util.Date;

public class CreativePO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_creative.id
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_creative.name
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_creative.type
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_creative.material_type
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private Byte materialType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_creative.height
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_creative.width
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private Integer width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_creative.size
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private Long size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_creative.duration
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_creative.audit_status
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private Byte auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_creative.user_id
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_creative.url
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_creative.create_time
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_creative.update_time
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_creative.id
     *
     * @return the value of ad_creative.id
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_creative.id
     *
     * @param id the value for ad_creative.id
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_creative.name
     *
     * @return the value of ad_creative.name
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_creative.name
     *
     * @param name the value for ad_creative.name
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_creative.type
     *
     * @return the value of ad_creative.type
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_creative.type
     *
     * @param type the value for ad_creative.type
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_creative.material_type
     *
     * @return the value of ad_creative.material_type
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public Byte getMaterialType() {
        return materialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_creative.material_type
     *
     * @param materialType the value for ad_creative.material_type
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setMaterialType(Byte materialType) {
        this.materialType = materialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_creative.height
     *
     * @return the value of ad_creative.height
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_creative.height
     *
     * @param height the value for ad_creative.height
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_creative.width
     *
     * @return the value of ad_creative.width
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_creative.width
     *
     * @param width the value for ad_creative.width
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_creative.size
     *
     * @return the value of ad_creative.size
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_creative.size
     *
     * @param size the value for ad_creative.size
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_creative.duration
     *
     * @return the value of ad_creative.duration
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_creative.duration
     *
     * @param duration the value for ad_creative.duration
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_creative.audit_status
     *
     * @return the value of ad_creative.audit_status
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public Byte getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_creative.audit_status
     *
     * @param auditStatus the value for ad_creative.audit_status
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setAuditStatus(Byte auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_creative.user_id
     *
     * @return the value of ad_creative.user_id
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_creative.user_id
     *
     * @param userId the value for ad_creative.user_id
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_creative.url
     *
     * @return the value of ad_creative.url
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_creative.url
     *
     * @param url the value for ad_creative.url
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_creative.create_time
     *
     * @return the value of ad_creative.create_time
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_creative.create_time
     *
     * @param createTime the value for ad_creative.create_time
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_creative.update_time
     *
     * @return the value of ad_creative.update_time
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_creative.update_time
     *
     * @param updateTime the value for ad_creative.update_time
     *
     * @mbg.generated Wed Aug 26 17:51:18 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}