spring:
  application:
    name: ad-gatway
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://server1:7001/eureka/, http://server2:7002/eureka/, http://server3:7003/eureka/