spring:
  application:
    name: ad-gatway
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://server1:7001/eureka/, http://server2:7002/eureka/, http://server3:7003/eureka/

zuul:
  prefix: /ad
  routes:
    sponsor:
      path: /sponsor/**
      serviceId: eureka-client-ad-sponsor
      strip-prefix: false
    search:
      path: /search/**
      serviceId: eureka-client-ad-search
      strip-prefix: false
    user:
      path: /user/**
      serviceId: eureka-client-ad-user
      strip-prefix: false

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key
  user-login-path: /user/login/**