server:
  port: 7000
  servlet:
    context-path: /sponsor
spring:
  application:
    name: eureka-client-ad-sponsor
  datasource:
    url: jdbc:mysql://localhost:3306/ad_data?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 10
      min-idle: 5
      initial-size: 2

eureka:
  client:
    service-url:
      defaultZone: http://server1:7001/eureka/, http://server2:7002/eureka/, http://server3:7003/eureka/
mybatis:
  mapper-locations: classpath:mapping/*.xml
